services:
    scrypted:
        container_name: scrypted
        image: koush/scrypted
        restart: unless-stopped
        network_mode: host
        environment:
            # Force Intel iHD driver for GPU Decoding
            - LIBVA_DRIVER_NAME=iHD
            - SCRPYTED_WEBLOADER_INVALIDATE=true
        devices:
            - /dev/dri/card0:/dev/dri/card0
            - /dev/dri/renderD129:/dev/dri/renderD129
        volumes:
            - /root/.scrypted/volume:/server/volume
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"
        dns:
            - ${SCRYPTED_DNS_SERVER_0:-1.1.1.1}
            - ${SCRYPTED_DNS_SERVER_1:-8.8.8.8}
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"

    watchtower:
        image: containrrr/watchtower
        container_name: scrypted-watchtower
        restart: unless-stopped
        environment:
            - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN:-env_missing_fallback}
            - WATCHTOWER_HTTP_API_UPDATE=true
            - WATCHTOWER_SCOPE=scrypted
            - WATCHTOWER_HTTP_API_PERIODIC_POLLS=${WATCHTOWER_HTTP_API_PERIODIC_POLLS:-true}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"
        ports:
            - 10444:8080
        command: --interval 3600 --cleanup --scope scrypted
        dns:
            - ${SCRYPTED_DNS_SERVER_0:-1.1.1.1}
            - ${SCRYPTED_DNS_SERVER_1:-8.8.8.8}
